[package]
name = "reth-zisk-stateless-validator-only-execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ziskos.workspace = true
reth-guest = { workspace = true, default-features = true }
guest-libs.workspace = true

reth-stateless.workspace = true
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-primitives-traits = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }

revm = { workspace = true, default-features = false, features = ["bn"] }
alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
    "serde",
    "sha3-keccak",
] }
k256.workspace = true
bincode.workspace = true
sha2.workspace = true
